### Pagina inicio
GET http://localhost:8090

### Recuperamos informacion de un documento json dentro de la aplicacion
GET http://localhost:8090/json

### Creamo un pokemon
POST http://localhost:8090/create
Content-Type: application/json

{
    "name" : "Ditto",
    "type" : "normal",
    "moves" : [
        "transform"
    ]
}